services:
  - type: web
    name: rotc-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    plan: free
    build:
      environment:
        python_version: 3.10.13
